name: CDK Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Install AWS CDK
      run: npm install -g aws-cdk
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Create venv
      run: python -m venv .venv

    - name: Activate venv
      run: |
        source .venv/bin/activate

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Cdk Bootstrap
      run: cdk bootstrap -c bucket_name=$BUCKET_NAME
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      working-directory: ./cdk

    - name: Cdk Synth
      run: cdk synth -c bucket_name=$BUCKET_NAME
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      working-directory: ./cdk
        
    - name: Cdk Deploy
      run: cdk deploy -c bucket_name=$BUCKET_NAME --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      working-directory: ./cdk
        
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: install dependencies
      run: npm install
      working-directory: ./react-app
      
      
    - name: react build
      run: npm run build 
      working-directory: ./react-app
      
    - name: Deploy
      run: aws s3 sync ./react-app/build s3://${{ secrets.BUCKET_NAME }}


    
